name: ai-twitter-bot

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  tweet_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # IMPORTANT: Allows pushing changes

      # Setting up Python and dependecies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Running the script with env variables
      - name: Run tweet script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_KEY_SECRET: ${{ secrets.X_API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        run: python3.11 main.py

      # Letting the github action to commit & push updated files(data/daily_tweet.txt & data/tweets.txt)
      - name: Commit updated data files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add data/
          git commit -m "Auto-update tweet history" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push || echo "Nothing to push"
